# Generated by Django 5.2.17 on 2026-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aboutsection_galleryimage_teammember_delete_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
